[profile.default]
libs = ["lib"]
optimizer = true
out = "out"
src = "src"
via_ir = true

remappings = [
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts",
  "@uniswap/v2-core/=lib/v2-core",
  "@uniswap/v2-periphery/=lib/v2-periphery",
]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = {key = "${ETHERSCAN_KEY}"}# Optional for verification

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
